---
- hosts: localhost
  vars_files:
    - config.yaml

  pre_tasks:
    - name: Ensure specified files are absent
      file:
        path: "/Applications/{{ item }}.app"
        state: absent
      become: true
      loop: "{{ preinstalled_apps_remove }}"
      tags: ['init', 'never']

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['always']
    - role: geerlingguy.mac.dock
      tags: ['init', 'never']

  # tasks: 
    # killall Dock
  
  