---
- hosts: localhost
  vars_files:
    - config.yaml

  pre_tasks:
    - name: Ensure specified files are absent
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ files_to_delete }}"
      tags: ['init']

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['always']
    - role: geerlingguy.mac.dock
      tags: ['init']
  
  